---
title: "Effects of covid-19 on tourism in Turkey"
author: 
  - Cogender, Ozden[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080384, [Github Repo](https://github.com/cogenderozden/Midterm)


# Introduction

The COVID-19 global epidemic, which emerged in China at the beginning of 2020 and then spread to the whole world, has affected many national, regional and global movements (human, capital, goods, trade, migration, etc.)@kervankiran2020bildiugimiz .It has had a huge impact especially on the tourism industry.The tourism sector in Turkey has been significantly affected by the Covid-19 outbreak. Turkey is one of the most popular travel destinations in the world and the tourism industry is an important source of income for the country's economy. However, the tourism sector in Turkey has been severely affected by the spread of the pandemic. Tourist numbers have decreased significantly as a result of border restrictions, flight cancellations and quarantine procedures. In addition, the epidemic caused employment losses and income reductions for those working in the tourism sector. Turkey has taken the necessary steps against COVID-19, but the recovery process for the travel and tourism sector can be long and difficult.In this study, the effects of covid-19 on the tourism sector in Turkey will be examined together with the data.


## Literature Review

Turkey's tourism sector has been heavily affected during the covid-19 process. Studies on its effects and evaluations in Turkey have been started.[@kervankiran2020bildiugimiz; @aydin2020yeni; @yenicsehirliouglu2020covid; @buyuk2020covid] Especially the entry bans to the countries that started to be implemented after the pandemic have caused great damage to the tourism sector in Turkey.In addition, people's insecurity about the cleanliness of hotels is one of the leading factors that negatively affect the effects of the pandemic on the tourism sector. The negative effects of the pandemic on the economy have also led people to cancel their holiday plans.


\newpage
# References {#references}
<div id="refs"></div>

